server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~* \.(css|js)$ {
    add_header Cache-Control "no-cache, must-revalidate" always;
    try_files $uri =404;
  }

  location / {
    add_header Cache-Control "no-store" always;
    try_files $uri $uri/ /index.html;
  }
}
